version: "3.8"
services:
  front-end:
    image: zuhaibali/sprint-front-end
    build:
      context: ./lbg-car-react-starter
      args:
        SERVER_URL: ${SERVER_URL}
    ports:
     - target: 80
       published: 80
  back-end:
    image: zuhaibali/sprint-back-end
    build:
      context: ./lbg-car-spring-app-starter
      args:
        SERVER_URL: ${SERVER_URL}
    ports:
     - target: 80
       published: 81